version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --log-level error
