---
- hosts: k8s
  become: true
  tasks:
    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Initialize Kubernetes Cluster
      command: kubeadm init
      register: kubeadm_output
      changed_when: True
      when: inventory_hostname == "server1"

    - name: Create .kube directory for kubectl configuration
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'
      when: inventory_hostname == "server1"

    - name: Copy Kubernetes config to user home
      command: cp -i /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config
      when: inventory_hostname == "server1"

    - name: Set kubectl context for root
      command: kubectl config set-context --current --namespace=default
      when: inventory_hostname == "server1"

    - name: Capture join token and CA cert hash
      command: kubeadm token create --print-join-command
      register: join_command
      when: inventory_hostname == "server1"

    - name: Join worker nodes to the cluster
      command: "{{ join_command.stdout }}"
      when: inventory_hostname == "server2"
