- name: Install Prometheus
  apt:
    name: prometheus
    state: present
  become: true

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  become: true

- name: Start Prometheus Service
  service:
    name: prometheus
    state: started
    enabled: true